#!/usr/bin/env bash


# dotbot job
set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# download vimplug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

sudo apt update
# install luarocks for lazy.nvim
if ! which luarocks >/dev/null 2>&1; then
    echo "Luarocks is not installed. Installing..."
    sudo apt install -y luarocks
    echo "Luarocks has been installed."
else
    echo "Luarocks is already installed."
fi
# python3-neovim and venv
apt install -y python3-neovim
PYTHON_VERSION=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
VENV_PACKAGE="python${PYTHON_VERSION}-venv"
sudo apt install -y $VENV_PACKAGE

if dpkg -l | grep -q $VENV_PACKAGE; then
    echo "$VENV_PACKAGE installed successfully."
else
    echo "Failed to install $VENV_PACKAGE."
fi

# ripgrep
apt install -y ripgrep

# install npm
curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
sudo apt install nodejs -y
sudo npm install -g typescript typescript-language-server
npm list -g --depth=0





