syntax enable
set number
set nowrap

" fold
"set foldmethod=indent
"set foldcolumn=2


" tab
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent



" PLUGINS
packloadall " Load all plugins.
silent! helptags ALL " load helpfile for all plugins

" shortcut
command! Bd :bp | :sp | :bn | :bd    " close buffer but keep window
command! Tree NERDTree


call plug#begin()

" Plug 'flazz/vim-colorschemes'
Plug 'sainnhe/sonokai'
Plug 'vim-python/python-syntax'
call plug#end()

colo sonokai

" Python
let g:python_highlight_all = 1
