syntax enable
set number
set nowrap

set pastetoggle=<F2>
set paste
" fold
"set foldmethod=indent
"set foldcolumn=2


" tab
set tabstop=4
set shiftwidth=4
set expandtab
" set autoindent
set spell

set background=dark " or light

" PLUGINS
packloadall " Load all plugins.
silent! helptags ALL " load helpfile for all plugins

" Important!!
if has('termguicolors')
  set termguicolors
endif

call plug#begin()
Plug 'sainnhe/gruvbox-material'
Plug 'sainnhe/edge'
Plug 'sainnhe/sonokai'
Plug 'vim-python/python-syntax'
call plug#end()

" edge 
let g:edge_style = 'aura'
let g:edge_better_performance = 1
" gruvbox
let g:gruvbox_material_background = 'soft' " Available values: 'hard', 'medium'(default), 'soft'
let g:gruvbox_material_better_performance = 1

" colorscheme gruvbox-material
" colorscheme edge
colo sonokai

" Python
let g:python_highlight_all = 1


" shortcut
command! Q quit

let mapleader = ","

inoremap <silent> jj <Esc>

nnoremap <silent> <C-e> 4<C-e>
nnoremap <silent> <C-y> 4<C-y>

" Map <leader>y in visual mode to copy via OSC 52
xnoremap <silent> <leader>y :<C-u>call CopyOSC52()<CR>

function! CopyOSC52()
  " Yank visually selected text to the unnamed register
  normal! ""y

  " Get the yanked text
  let l:text = getreg('"')
  let l:text_escaped = shellescape(l:text, 1)
  let l:base64_part = '$(echo ' . l:text_escaped . ' | base64 | tr -d "\n")'
  let l:osc52_prefix = "printf '\033]52;c;"
  let l:osc52_suffix = "\a'"
  let l:cmd = l:osc52_prefix . l:base64_part . l:osc52_suffix
  echom l:cmd 
" call system(l:cmd)

endfunction



